/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sh.tools.liblognormjava;

public interface liblognormConstants {
  public final static int LN_NOMEM = liblognormJNI.LN_NOMEM_get();
  public final static int LN_INVLDFDESCR = liblognormJNI.LN_INVLDFDESCR_get();
  public final static int LN_BADCONFIG = liblognormJNI.LN_BADCONFIG_get();
  public final static int LN_BADPARSERSTATE = liblognormJNI.LN_BADPARSERSTATE_get();
  public final static int LN_WRONGPARSER = liblognormJNI.LN_WRONGPARSER_get();
  public final static int LN_RB_LINE_TOO_LONG = liblognormJNI.LN_RB_LINE_TOO_LONG_get();
  public final static int LN_OVER_SIZE_LIMIT = liblognormJNI.LN_OVER_SIZE_LIMIT_get();
  public final static int LN_CTXOPT_ALLOW_REGEX = liblognormJNI.LN_CTXOPT_ALLOW_REGEX_get();
  public final static int LN_CTXOPT_ADD_EXEC_PATH = liblognormJNI.LN_CTXOPT_ADD_EXEC_PATH_get();
  public final static int LN_CTXOPT_ADD_ORIGINALMSG = liblognormJNI.LN_CTXOPT_ADD_ORIGINALMSG_get();
  public final static int LN_CTXOPT_ADD_RULE = liblognormJNI.LN_CTXOPT_ADD_RULE_get();
  public final static int LN_CTXOPT_ADD_RULE_LOCATION = liblognormJNI.LN_CTXOPT_ADD_RULE_LOCATION_get();
}
