/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sh.tools.liblognormjava;

public class liblognorm implements liblognormConstants {
  public static String ln_version() {
    return liblognormJNI.ln_version();
  }

  public static int ln_hasAdvancedStats() {
    return liblognormJNI.ln_hasAdvancedStats();
  }

  public static SWIGTYPE_p_ln_ctx_s ln_initCtx() {
    long cPtr = liblognormJNI.ln_initCtx();
    return (cPtr == 0) ? null : new SWIGTYPE_p_ln_ctx_s(cPtr, false);
  }

  public static SWIGTYPE_p_ln_ctx_s ln_inherittedCtx(SWIGTYPE_p_ln_ctx_s parent) {
    long cPtr = liblognormJNI.ln_inherittedCtx(SWIGTYPE_p_ln_ctx_s.getCPtr(parent));
    return (cPtr == 0) ? null : new SWIGTYPE_p_ln_ctx_s(cPtr, false);
  }

  public static int ln_exitCtx(SWIGTYPE_p_ln_ctx_s ctx) {
    return liblognormJNI.ln_exitCtx(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx));
  }

  public static void ln_setCtxOpts(SWIGTYPE_p_ln_ctx_s ctx, long opts) {
    liblognormJNI.ln_setCtxOpts(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), opts);
  }

  public static int ln_setDebugCB(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_f_p_void_p_q_const__char_size_t__void cb, SWIGTYPE_p_void cookie) {
    return liblognormJNI.ln_setDebugCB(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_f_p_void_p_q_const__char_size_t__void.getCPtr(cb), SWIGTYPE_p_void.getCPtr(cookie));
  }

  public static int ln_setErrMsgCB(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_f_p_void_p_q_const__char_size_t__void cb, SWIGTYPE_p_void cookie) {
    return liblognormJNI.ln_setErrMsgCB(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_f_p_void_p_q_const__char_size_t__void.getCPtr(cb), SWIGTYPE_p_void.getCPtr(cookie));
  }

  public static void ln_enableDebug(SWIGTYPE_p_ln_ctx_s ctx, int i) {
    liblognormJNI.ln_enableDebug(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), i);
  }

  public static int ln_loadSamples(SWIGTYPE_p_ln_ctx_s ctx, String file) {
    return liblognormJNI.ln_loadSamples(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), file);
  }

  public static int ln_loadSamplesFromString(SWIGTYPE_p_ln_ctx_s ctx, String string) {
    return liblognormJNI.ln_loadSamplesFromString(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), string);
  }

  public static int ln_normalize(SWIGTYPE_p_ln_ctx_s ctx, String str, long strLen, SWIGTYPE_p_p_json_object json_p) {
    return liblognormJNI.ln_normalize(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), str, strLen, SWIGTYPE_p_p_json_object.getCPtr(json_p));
  }

  public static String ln_normalize_sh(SWIGTYPE_p_ln_ctx_s ctx, String rawmsg, String encoding, int eventTags) {
    return liblognormJNI.ln_normalize_sh(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), rawmsg, encoding, eventTags);
  }

  public static String genDOT_string_sh(SWIGTYPE_p_ln_ctx_s ctx) {
    return liblognormJNI.genDOT_string_sh(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx));
  }

  public static int genDOT_file_sh(SWIGTYPE_p_ln_ctx_s ctx, String dotFile) {
    return liblognormJNI.genDOT_file_sh(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), dotFile);
  }

  public static int ln_setErrMsgCB_sh(SWIGTYPE_p_ln_ctx_s ctx, String logFilename) {
    return liblognormJNI.ln_setErrMsgCB_sh(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), logFilename);
  }

  public static int ln_setDbgMsgCB_sh(SWIGTYPE_p_ln_ctx_s ctx, String logFilename) {
    return liblognormJNI.ln_setDbgMsgCB_sh(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), logFilename);
  }

  public static int ln_constructRFC5424Date(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructRFC5424Date(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseRFC5424Date(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseRFC5424Date(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructRFC5424Date(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructRFC5424Date(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_constructRFC3164Date(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructRFC3164Date(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseRFC3164Date(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseRFC3164Date(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructRFC3164Date(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructRFC3164Date(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_constructNumber(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructNumber(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseNumber(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseNumber(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructNumber(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructNumber(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_constructFloat(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructFloat(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseFloat(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseFloat(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructFloat(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructFloat(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_constructHexNumber(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructHexNumber(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseHexNumber(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseHexNumber(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructHexNumber(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructHexNumber(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseKernelTimestamp(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseKernelTimestamp(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseWhitespace(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseWhitespace(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseWord(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseWord(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_constructStringTo(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructStringTo(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseStringTo(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseStringTo(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructStringTo(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructStringTo(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseAlpha(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseAlpha(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_constructLiteral(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructLiteral(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseLiteral(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseLiteral(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructLiteral(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructLiteral(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_constructCharTo(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructCharTo(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseCharTo(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseCharTo(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructCharTo(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructCharTo(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_constructCharSeparated(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructCharSeparated(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseCharSeparated(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseCharSeparated(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructCharSeparated(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructCharSeparated(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_constructRepeat(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructRepeat(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseRepeat(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseRepeat(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructRepeat(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructRepeat(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_constructString(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructString(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseString(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseString(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructString(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructString(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseRest(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseRest(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseOpQuotedString(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseOpQuotedString(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseQuotedString(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseQuotedString(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseISODate(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseISODate(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseTime12hr(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseTime12hr(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseTime24hr(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseTime24hr(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseDuration(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseDuration(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseIPv4(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseIPv4(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseIPv6(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseIPv6(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseJSON(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseJSON(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseCEESyslog(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseCEESyslog(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parsev2IPTables(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parsev2IPTables(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseCiscoInterfaceSpec(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseCiscoInterfaceSpec(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseMAC48(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseMAC48(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_v2_parseCEF(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseCEF(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_constructCheckpointLEA(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_p_void pdata) {
    return liblognormJNI.ln_constructCheckpointLEA(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseCheckpointLEA(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseCheckpointLEA(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static void ln_destructCheckpointLEA(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_void pdata) {
    liblognormJNI.ln_destructCheckpointLEA(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_void.getCPtr(pdata));
  }

  public static int ln_v2_parseNameValue(SWIGTYPE_p_npb_t npb, SWIGTYPE_p_size_t offs, SWIGTYPE_p_void arg2, SWIGTYPE_p_size_t parsed, SWIGTYPE_p_p_json_object value) {
    return liblognormJNI.ln_v2_parseNameValue(SWIGTYPE_p_npb_t.getCPtr(npb), SWIGTYPE_p_size_t.getCPtr(offs), SWIGTYPE_p_void.getCPtr(arg2), SWIGTYPE_p_size_t.getCPtr(parsed), SWIGTYPE_p_p_json_object.getCPtr(value));
  }

  public static int ln_combineData_Literal(SWIGTYPE_p_void org, SWIGTYPE_p_void add) {
    return liblognormJNI.ln_combineData_Literal(SWIGTYPE_p_void.getCPtr(org), SWIGTYPE_p_void.getCPtr(add));
  }

  public static ln_annotSet_s ln_newAnnotSet(SWIGTYPE_p_ln_ctx_s ctx) {
    long cPtr = liblognormJNI.ln_newAnnotSet(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx));
    return (cPtr == 0) ? null : new ln_annotSet_s(cPtr, false);
  }

  public static void ln_deleteAnnotSet(ln_annotSet_s as) {
    liblognormJNI.ln_deleteAnnotSet(ln_annotSet_s.getCPtr(as), as);
  }

  public static ln_annot_s ln_findAnnot(ln_annotSet_s as, SWIGTYPE_p_es_str_t tag) {
    long cPtr = liblognormJNI.ln_findAnnot(ln_annotSet_s.getCPtr(as), as, SWIGTYPE_p_es_str_t.getCPtr(tag));
    return (cPtr == 0) ? null : new ln_annot_s(cPtr, false);
  }

  public static int ln_addAnnotToSet(ln_annotSet_s as, ln_annot_s annot) {
    return liblognormJNI.ln_addAnnotToSet(ln_annotSet_s.getCPtr(as), as, ln_annot_s.getCPtr(annot), annot);
  }

  public static ln_annot_s ln_newAnnot(SWIGTYPE_p_es_str_t tag) {
    long cPtr = liblognormJNI.ln_newAnnot(SWIGTYPE_p_es_str_t.getCPtr(tag));
    return (cPtr == 0) ? null : new ln_annot_s(cPtr, false);
  }

  public static void ln_deleteAnnot(ln_annot_s annot) {
    liblognormJNI.ln_deleteAnnot(ln_annot_s.getCPtr(annot), annot);
  }

  public static int ln_addAnnotOp(ln_annot_s anot, ln_annot_opcode opc, SWIGTYPE_p_es_str_t name, SWIGTYPE_p_es_str_t value) {
    return liblognormJNI.ln_addAnnotOp(ln_annot_s.getCPtr(anot), anot, opc.swigValue(), SWIGTYPE_p_es_str_t.getCPtr(name), SWIGTYPE_p_es_str_t.getCPtr(value));
  }

  public static int ln_annotate(SWIGTYPE_p_ln_ctx_s ctx, SWIGTYPE_p_json_object json, SWIGTYPE_p_json_object tags) {
    return liblognormJNI.ln_annotate(SWIGTYPE_p_ln_ctx_s.getCPtr(ctx), SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_json_object.getCPtr(tags));
  }

  public static int ln_fmtEventToRFC5424(SWIGTYPE_p_json_object json, SWIGTYPE_p_p_es_str_t str) {
    return liblognormJNI.ln_fmtEventToRFC5424(SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_es_str_t.getCPtr(str));
  }

  public static int ln_fmtEventToCSV(SWIGTYPE_p_json_object json, SWIGTYPE_p_p_es_str_t str, SWIGTYPE_p_es_str_t extraData) {
    return liblognormJNI.ln_fmtEventToCSV(SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_es_str_t.getCPtr(str), SWIGTYPE_p_es_str_t.getCPtr(extraData));
  }

  public static int ln_fmtEventToXML(SWIGTYPE_p_json_object json, SWIGTYPE_p_p_es_str_t str) {
    return liblognormJNI.ln_fmtEventToXML(SWIGTYPE_p_json_object.getCPtr(json), SWIGTYPE_p_p_es_str_t.getCPtr(str));
  }

}
