/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sh.tools.liblognormjava;

public class ln_annot_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ln_annot_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ln_annot_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liblognormJNI.delete_ln_annot_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNext(ln_annot_s value) {
    liblognormJNI.ln_annot_s_next_set(swigCPtr, this, ln_annot_s.getCPtr(value), value);
  }

  public ln_annot_s getNext() {
    long cPtr = liblognormJNI.ln_annot_s_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ln_annot_s(cPtr, false);
  }

  public void setTag(SWIGTYPE_p_es_str_t value) {
    liblognormJNI.ln_annot_s_tag_set(swigCPtr, this, SWIGTYPE_p_es_str_t.getCPtr(value));
  }

  public SWIGTYPE_p_es_str_t getTag() {
    long cPtr = liblognormJNI.ln_annot_s_tag_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_es_str_t(cPtr, false);
  }

  public void setOproot(ln_annot_op_s value) {
    liblognormJNI.ln_annot_s_oproot_set(swigCPtr, this, ln_annot_op_s.getCPtr(value), value);
  }

  public ln_annot_op_s getOproot() {
    long cPtr = liblognormJNI.ln_annot_s_oproot_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ln_annot_op_s(cPtr, false);
  }

  public ln_annot_s() {
    this(liblognormJNI.new_ln_annot_s(), true);
  }

}
