/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sh.tools.liblognormjava;

public final class ln_annot_opcode {
  public final static ln_annot_opcode ln_annot_ADD = new ln_annot_opcode("ln_annot_ADD", liblognormJNI.ln_annot_ADD_get());
  public final static ln_annot_opcode ln_annot_RM = new ln_annot_opcode("ln_annot_RM", liblognormJNI.ln_annot_RM_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ln_annot_opcode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ln_annot_opcode.class + " with value " + swigValue);
  }

  private ln_annot_opcode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ln_annot_opcode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ln_annot_opcode(String swigName, ln_annot_opcode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ln_annot_opcode[] swigValues = { ln_annot_ADD, ln_annot_RM };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

