/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sh.tools.liblognormjava;

public class ln_annot_op_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ln_annot_op_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ln_annot_op_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liblognormJNI.delete_ln_annot_op_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNext(ln_annot_op_s value) {
    liblognormJNI.ln_annot_op_s_next_set(swigCPtr, this, ln_annot_op_s.getCPtr(value), value);
  }

  public ln_annot_op_s getNext() {
    long cPtr = liblognormJNI.ln_annot_op_s_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ln_annot_op_s(cPtr, false);
  }

  public void setOpc(ln_annot_opcode value) {
    liblognormJNI.ln_annot_op_s_opc_set(swigCPtr, this, value.swigValue());
  }

  public ln_annot_opcode getOpc() {
    return ln_annot_opcode.swigToEnum(liblognormJNI.ln_annot_op_s_opc_get(swigCPtr, this));
  }

  public void setName(SWIGTYPE_p_es_str_t value) {
    liblognormJNI.ln_annot_op_s_name_set(swigCPtr, this, SWIGTYPE_p_es_str_t.getCPtr(value));
  }

  public SWIGTYPE_p_es_str_t getName() {
    long cPtr = liblognormJNI.ln_annot_op_s_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_es_str_t(cPtr, false);
  }

  public void setValue(SWIGTYPE_p_es_str_t value) {
    liblognormJNI.ln_annot_op_s_value_set(swigCPtr, this, SWIGTYPE_p_es_str_t.getCPtr(value));
  }

  public SWIGTYPE_p_es_str_t getValue() {
    long cPtr = liblognormJNI.ln_annot_op_s_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_es_str_t(cPtr, false);
  }

  public ln_annot_op_s() {
    this(liblognormJNI.new_ln_annot_op_s(), true);
  }

}
