/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sh.tools.liblognormjava;

public class ln_annotSet_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ln_annotSet_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ln_annotSet_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liblognormJNI.delete_ln_annotSet_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAroot(ln_annot_s value) {
    liblognormJNI.ln_annotSet_s_aroot_set(swigCPtr, this, ln_annot_s.getCPtr(value), value);
  }

  public ln_annot_s getAroot() {
    long cPtr = liblognormJNI.ln_annotSet_s_aroot_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ln_annot_s(cPtr, false);
  }

  public void setCtx(SWIGTYPE_p_ln_ctx_s value) {
    liblognormJNI.ln_annotSet_s_ctx_set(swigCPtr, this, SWIGTYPE_p_ln_ctx_s.getCPtr(value));
  }

  public SWIGTYPE_p_ln_ctx_s getCtx() {
    long cPtr = liblognormJNI.ln_annotSet_s_ctx_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ln_ctx_s(cPtr, false);
  }

  public ln_annotSet_s() {
    this(liblognormJNI.new_ln_annotSet_s(), true);
  }

}
